### ISSUE TITLE
Website button links shoud be updatet to this github

### ISSUE THREAD

**Issue by develcooking** [ramidzkh/villager-trading-station#2]
Website button link should be updated to this github

So if you are in the mod menu and press on the website button or on the issues button you get to the github page of the mod Applied-Botanics (https://github.com/ramidzkh/Applied-Botanics#readme) and the issues page of that
Its a small issue so i hope you can fix it in a future update

Ps:
Powerful mod that is really nice especially combind thith tom's simpel storage mod
sadly this mod leads to frequent crashes on my server

**Comment by ramidzkh** [comment]
oh haha left that in from copying the mod structure.

>  Powerful mod that is really nice especially combind thith tom's simpel storage mod
sadly this mod leads to frequent crashes on my server

Could you open an issue with the crash report or how the crash occurs?
