### ISSUE TITLE
Mod doesn't appear to be working?

### ISSUE THREAD

**Issue by ImMorphi** [ramidzkh/villager-trading-station#4]
I'll preface this with the fact that I'm not sure if its not working or super slow. I have a villager that trades 24x Basalt for 1x Emerald. I read the mod page for how to do the quotes and believe I've set it up correctly, in the villager trader station.  The villager that does the trade is stuck directly next to the trading station.
I've spent about an hour waiting yet no trade has occurred? 
Playing on all the fabric 6 (mod version included is villager-trading-station-1.1.0).
![Base Profile Screenshot 2023 09 30 - 23 07 04 52](https://github.com/ramidzkh/villager-trading-station/assets/146550239/76b67a39-ef34-48af-818c-bc12e44ea032)

**Comment by ramidzkh** [comment]
I assume the villager has this exact trade (no discounts or anything). Is this a problem with just this villager or is it broken with everyone?

**Comment by ImMorphi** [comment]
I've got two villagers, the exact trade (no discounts or anything) is 24 basalt for 1 Emerald. The other composter villager has the exact quote 1x Emerald for 1x Cake. I had the chunk loaded overnight with 4 stacks of basalt and a stack of emerald in the trading station, however still same issue they didn't trade once.

**Comment by ImMorphi** [comment]
I'm going to close this but apparently it just started working, and they did all the trades instantly. I hadn't changed anything other than doing a quick manual trade with the villagers for each of the wanted trades.
